### ISSUE TITLE
What is the difference with tern-cordovajs?

### ISSUE THREAD

**Issue by angelozerr** [albertinad/cordova-plugins-tern-condense#1]
@albertinad have you seen https://github.com/vrubezhny/tern-cordovajs

It should be cool if we have one tern plugin for cordova instead of having several. What do you think about that?

**Comment by albertinad** [comment]
Hi @angelozerr , I took a look at your plugin, and gave it a try, but both of them, are for different purposes. The plugin you suggest works with tern only, please correct me if I'm wrong :), and makes tern to know about the cordova API, but not cordova plugins APIs. 
The initial goal of cordova-plugins-tern-condense is to hook up to condense, and based on the configuration file, automatically generate the definition for any plugin. Then you can save that definition and use it with tern, but the plugin itself doesn't expose any static definition since cordova plugins are many and always we have new plugins.

**Comment by angelozerr** [comment]
Thanks @albertinad for your information.

> The plugin you suggest works with tern only, please correct me if I'm wrong :), 

Yes that is it.

> The initial goal of cordova-plugins-tern-condense is to hook up to condense, and based on the configuration file, automatically generate the definition for any plugin. 

Have you a sample of generated definition files? I would like to know if I could integrate your work for https://github.com/angelozerr/tern.java/ and improve support for Cordova https://github.com/angelozerr/tern.java/wiki/Tern-&-CordovaJS-support
